[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "easypyside"
dynamic = ["version"]
description = "Simple wrapper for PySide6"
readme = "README.md"
license = { file = "LICENSE" }
authors = [
  { name="Pablo GP", email="pablogonzalezpila@gmail.com" }
]
requires-python = ">=3.8"
dependencies = [
  "PySide6",
  # "pandas",
  # "markdown2"
]

[project.optional-dependencies]
pandas = ["pandas"]
markdown = ["markdown2"]
all = [ "easypyside[pandas,markdown]", ]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]
include = ["easypyside*"]

[tool.setuptools.package-data]
easypyside = ["__forms/*"]

[tool.setuptools.dynamic]
version = { attr = "easypyside.__version__" }

[project.urls]
"Homepage" = "https://github.com/PaulFilms/EasyPySide"
"Documentation" = "https://github.com/PaulFilms/EasyPySide/blob/main/README.md"
"Bug Tracker" = "https://github.com/PaulFilms/EasyPySide/issues"
